name: CI/CD Pipeline for PHP Docker Application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run unit tests
      run: vendor/bin/phpunit

    - name: Run static analysis
      run: vendor/bin/phpstan analyse src tests

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: design399/crm_docker:${{ github.sha }}

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Deploy to Dev
      run: |
        docker pull design399/crm_docker:${{ github.sha }}
        docker stop dev_container || true
        docker rm dev_container || true
        docker run -d -p 8080:80 --name dev_container design399/crm_docker:${{ github.sha }}
        echo "Deployed to Dev environment"

  deploy-qa:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: Deploy to QA
      run: |
        docker pull design399/crm_docker:${{ github.sha }}
        docker stop qa_container || true
        docker rm qa_container || true
        docker run -d -p 8081:80 --name qa_container design399/crm_docker:${{ github.sha }}
        echo "Deployed to QA environment"

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy to Production
      run: |
        docker pull design399/crm_docker:${{ github.sha }}
        docker stop prod_container || true
        docker rm prod_container || true
        docker run -d -p 8082:80 --name prod_container design399/crm_docker:${{ github.sha }}
        echo "Deployed to Production environment"
