name: Build, Push, Pull, and Deploy Docker image to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y php php-cli php-mbstring php-xml
      - name: Create tests directory and file
        run: |
          mkdir -p tests
          echo "<?php echo 'Test running successfully';" > tests/test.php
      - name: Run tests
        run: php tests/test.php
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: DockerfileFolder/
          push: true
          tags: design399/crm_docker:latest

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy to Dev
        run: |
          docker run -d -p 8080:80 --name dev_container design399/crm_docker:latest
          echo "Deploying to Dev environment"

  deploy-qa:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Deploy to Q/A
        run: |
          docker run -d -p 8081:80 --name qa_container design399/crm_docker:latest
          echo "Deploying to Q/A environment"

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production (Docker)
        run: |
          docker run -d -p 8082:80 --name prod_container design399/crm_docker:latest
          echo "Deploying to Production environment"

      - name: Deploy to Production (cPanel)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
        
