name: Build, Test, Push, and Deploy Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests
      run: vendor/bin/phpunit

    - name: Build Docker image
      run: docker build -t design399/crm_docker:${{ github.sha }} .

    - name: Run container tests
      run: |
        docker run --name test_container -d -p 8080:80 design399/crm_docker:${{ github.sha }}
        sleep 10
        curl -sSf http://localhost:8080 || exit 1
        docker stop test_container

  push-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t design399/crm_docker:${{ github.sha }} .
        docker push design399/crm_docker:${{ github.sha }}

    - name: Deploy to Dev
      env:
        APP_ENV: dev
        PORT: 8080
        TAG: ${{ github.sha }}
      run: |
        docker-compose up -d
        echo "Deployed to Dev environment"

    - name: Deploy to QA
      env:
        APP_ENV: qa
        PORT: 8081
        TAG: ${{ github.sha }}
      run: |
        docker-compose up -d
        echo "Deployed to QA environment"

    - name: Deploy to Production
      env:
        APP_ENV: production
        PORT: 8082
        TAG: ${{ github.sha }}
      run: |
        docker-compose up -d
        echo "Deployed to Production environment"
