name: Build, Push, Pull, and Deploy Docker image to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Reference your environment here
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y php php-cli php-mbstring php-xml
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can specify the Node.js version you need
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: design399/crm_docker:latest
      
      # Add any additional deployment steps here
    
         
         
