name: Build, Push, Pull, and Deploy Docker image to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Default environment; will be overridden by deployment steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y php php-cli php-mbstring php-xml
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1  # Specify the Node.js version you need
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: DockerfileFolder/
          push: true
          tags: design399/crm_docker:latest
      
      - name: Deploy to Dev
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Dev environment"
          # Add deployment commands for Dev environment here
        env:
          ENVIRONMENT: dev

      - name: Deploy to Q/A
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Q/A environment"
          # Add deployment commands for Q/A environment here
        env:
          ENVIRONMENT: qa

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Production environment"
          # Add deployment commands for Production environment here
        env:
          ENVIRONMENT: production

    
         
         
