name: Docker CI/CD
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up PHP
      run: |
        sudo apt-get update
        sudo apt-get install -y php php-cli php-mbstring php-xml
    
    - name: Run tests
      run: |
        mkdir -p tests
        echo "<?php echo 'Test running successfully';" > tests/test.php
        php tests/test.php
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: design399/crm_docker:latest
    
    - name: Deploy to Dev
      run: |
        echo "Deploying to Dev environment"
        docker stop dev_container || true
        docker rm dev_container || true
        docker run -d -p 8080:80 --name dev_container design399/crm_docker:latest
    
    - name: Deploy to Q/A
      run: |
        echo "Deploying to Q/A environment"
        docker stop qa_container || true
        docker rm qa_container || true
        docker run -d -p 8081:80 --name qa_container design399/crm_docker:latest
    
    - name: Deploy to Production (Docker)
      run: |
        echo "Deploying to Production environment"
        docker stop prod_container || true
        docker rm prod_container || true
        docker run -d -p 8082:80 --name prod_container design399/crm_docker:latest
    
    - name: Deploy to Production (cPanel)
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_SERVER_DIR }}/
        local-dir: ./
